name: Rust

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Add Target
      run: rustup target add thumbv6m-none-eabi
    - name: Install GCC and binutils
      run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi
    - name: Add llvm tooling
      run: rustup component add llvm-tools-preview
    - name: Build
      run: cargo objcopy --release -- -O binary rusty-firmware.bin
